name: postjob
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inset_box_shadow: ^1.0.8
  get: ^4.6.6
  hive_flutter:
  uuid:
  firebase_core:
  firebase_storage: ^12.0.1
  file_picker: ^8.0.5
  firebase_auth: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
     - family: Jost
       fonts:
       - asset: assets/fonts/Jost-Regular.ttf
       - asset: assets/fonts/Jost-Bold.ttf
         weight: 700
       - asset: assets/fonts/Jost-Medium.ttf
         weight: 500
       - asset: assets/fonts/Jost-Thin.ttf
         weight: 100
       - asset: assets/fonts/Jost-Light.ttf
         weight: 300
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
